# Generated by Django 5.0.1 on 2024-01-21 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamperNightPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=210)),
                ('description', models.TextField(blank=True, null=True)),
                ('free', models.BooleanField(default=False)),
                ('wc', models.BooleanField(default=False)),
                ('drinking_water', models.BooleanField(default=False)),
                ('tables', models.BooleanField(default=False)),
                ('gray_sink', models.BooleanField(default=False)),
                ('black_sink', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=210)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCamperNightPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=210)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.campernightpoint'))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('camper_night_point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.campernightpoint')),
            ],
        ),
        migrations.CreateModel(
            name='InterestPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=210)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='maps.category')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInterestPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=210)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.interestpoint'))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('interest_point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.interestpoint')),
            ],
        ),
    ]
