# Generated by Django 5.0.1 on 2024-01-21 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d36c6e65-3212-4638-a44d-995cc48094da'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('87a914b9-daf7-4e98-947a-ccbd63fa62a9'), primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInterestPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7a67813c-726b-49d7-a1f6-94f72fb15505'), primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('interest_point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.interestpoint')),
            ],
        ),
    ]
