# Generated by Django 5.0.1 on 2024-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campernightpoint',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campernightpoint',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campernightpoint',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campernightpoint',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campernightpoint',
            name='postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campernightpoint',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campernightpoint',
            name='region_abbr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campernightpoint',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
