# Generated by Django 5.0.1 on 2024-01-21 15:44

import apps.maps.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('089d62fe-8fca-4e78-9852-301349fb20f7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imageinterestpoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48e1c484-3c5a-428c-9160-2d29a235bcee'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imageinterestpoint',
            name='image',
            field=models.ImageField(upload_to=apps.maps.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='interestpoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4aa950ac-dab5-4b05-bfcf-25be35421125'), primary_key=True, serialize=False, unique=True),
        ),
    ]
