# Generated by Django 5.0.1 on 2024-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_campernightpoint_address_campernightpoint_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestpoint',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='region_abbr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
