# Generated by Django 5.0.1 on 2024-01-21 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_categories_id_alter_imageinterestpoint_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de910423-2ef4-4c11-b11f-e239dc66ad8f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imageinterestpoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39c66bd4-6973-4647-a91b-91ef602ae95f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='interestpoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23a96739-f2fd-49cb-9b19-d516596b91ab'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
