# Generated by Django 5.0.1 on 2024-01-21 21:49

import apps.maps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_campernightpoint_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecampernightpoint',
            name='image',
            field=models.ImageField(upload_to=apps.maps.models.camper_night_point_upload_to),
        ),
        migrations.AlterField(
            model_name='imageinterestpoint',
            name='image',
            field=models.ImageField(upload_to=apps.maps.models.interest_point_upload_to),
        ),
    ]
