# Generated by Django 5.0.1 on 2024-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_categories_id_alter_imageinterestpoint_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestpoint',
            name='category',
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='category',
            field=models.ManyToManyField(to='maps.categories'),
        ),
    ]
