# Generated by Django 5.0.1 on 2024-01-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_imagecampernightpoint_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestpoint',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
