# Generated by Django 5.0.1 on 2024-01-21 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_remove_interestpoint_category_interestpoint_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamperNightPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('free', models.BooleanField()),
                ('wc', models.BooleanField()),
                ('drinking_water', models.BooleanField()),
                ('gray_sink', models.BooleanField()),
                ('black_sink', models.BooleanField()),
                ('electricity', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imageinterestpoint',
            name='interest_point_id',
        ),
        migrations.AddField(
            model_name='interestpoint',
            name='images',
            field=models.ManyToManyField(to='maps.imageinterestpoint'),
        ),
    ]
