# Generated by Django 5.0.1 on 2024-01-27 23:21

import apps.maps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_interestpoint_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campernightpoint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.maps.models.interest_point_upload_to),
        ),
    ]
