# Generated by Django 5.0.1 on 2024-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_campernightpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campernightpoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageinterestpoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interestpoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
