# Generated by Django 5.0.1 on 2024-01-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_alter_campernightpoint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campernightpoint',
            name='tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campernightpoint',
            name='black_sink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campernightpoint',
            name='drinking_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campernightpoint',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campernightpoint',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campernightpoint',
            name='gray_sink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campernightpoint',
            name='wc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campernightpoint',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
