# Generated by Django 5.0.1 on 2024-01-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_campernightpoint_tables_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
